import localFont from "next/font/local";
import "./globals.css";


const rx100 = localFont({
  src: [
    { path: "./font/rx100.woff2", weight: "300", style: "normal" },
  ],
  variable: "--font-rx100",
  fallback: ["Courier New", "monospace"],
});
const minecraft = localFont({
  src: [
    { path: "./font/Minecraft.woff2", weight: "300", style: "normal" },
  ],
  variable: "--font-Minecraft",
  fallback: ["Courier New", "monospace"],
});
const alagard = localFont({
  src: [
    { path: "./font/alagard.woff2", weight: "300", style: "normal" },
  ],
  variable: "--font-alagard",
  fallback: ["Courier New", "monospace"],
});
const Gamer = localFont({
  src: [
    { path: "./font/Gamer.woff2", weight: "300", style: "normal" },
  ],
  variable: "--font-Gamer",
  fallback: ["Courier New", "monospace"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${rx100.variable} ${minecraft.variable} ${alagard.variable} ${Gamer.variable} h-full antialiased`}
    >
      <body className="bg-black min-h-full flex flex-col">{children}</body>
    </html>
  );
}
